name: Ruby
on: [push, pull_request]
jobs:
  specs:
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7'] # TODO: 3.0 support

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake
